aisingapore/PeekingDuck

- tests/pipeline/nodes/input/test_recorded.py
Edit the config used in testing to match the changes needed for image resizing. Closes #262 .
> changed test_recorded test config

- peekingduck/pipeline/pipeline.py
Requesting review from @sidney-tio as wildcard pipeline work may be closely related to #66 
closes #257
> feat(core): reserve 'all' as wildcard keyword

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Include contributing docs instructions for people who want to contribute to PeekingDuck.
> Contributing info

- .github/workflows/code_check.yml
- .github/workflows/mlmodel_tests.yml
- pyproject.toml
- scripts/mlmodel_tests.sh
- scripts/unit_tests.sh
- tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
- tests/pipeline/nodes/model/posenetv1/test_posenet.py
- tests/pipeline/nodes/model/yolov4/test_yolo.py
This merge separates unit tests from mlmodel tests. With this merge it will be possible to run unit test more frequently. 
closes #173
> Separate tests

- peekingduck/pipeline/nodes/output/media_writer.py
- tests/conftest.py
- tests/pipeline/nodes/output/test_media_writer.py
Made modification to check the filename of the saved video to include timestamp using regex pattern matching.
follow up for #259
> modify the test to cater for timestamp in filename of output saved video

- .github/workflows/mlmodel_tests.yml
- tests/pipeline/nodes/model/posenetv1/test_predictor.py
This is a fix to the unit test. The posenet predictor fails when not run with the other mlmodel tests.
> ci(cicd-infra): minor fixes

- README.md
- docs/source/introduction/README.md
- docs/source/models/efficientdet.md
- docs/source/models/hrnet.md
- docs/source/models/posenet.md
- docs/source/models/yolo.md
- peekingduck/loaders.py
- tests/loaders/test_declarativeloader.py
- use_cases/group_size_checking.yml
- use_cases/object_counting.yml
- use_cases/social_distancing.yml
- use_cases/zone_counting.yml
> run_config.yml to be read as list of nested dictionaries, and allow changing of nested configs.

- peekingduck/configs/output/csv_writer.yml
- peekingduck/pipeline/nodes/output/csv_writer.py
- peekingduck/pipeline/nodes/output/utils/__init__.py
- peekingduck/pipeline/nodes/output/utils/csvlogger.py
- tests/pipeline/nodes/output/test_csv_writer.py
A new node that logs user defined statistics  in a csv file
1. csv file name will be appended with timestamp
2. only valid statistics that are found in data pool will be included in the csv file
3. warning msg will be displayed in terminal stating invalid statistics not found in data pool
4. logging interval is in terms of seconds
closes #274
> feat(output.csv_writer): new node to output csv file for logging key statistics

- tests/pipeline/nodes/model/hrnetv1/test_detector.py
- tests/pipeline/nodes/model/hrnetv1/test_hrnet_model.py
Fix unit testing error: 
Added weight checker and downloader to prevent error when directly calling detector for unit testing
> fix(unittest): Add weight checker and downloaders

- docs/source/introduction/guide_custom_nodes.md
Add section to guide user to creating unique custom nodes folder.
> Build(doc): Add section to guide user to create unique custom folder

- peekingduck/pipeline/nodes/draw/poses.py
- peekingduck/pipeline/nodes/draw/utils/drawfunctions.py
- peekingduck/pipeline/nodes/draw/utils/pose.py
Part of Issue #250. Add draw pose util files and refactored draw pose node to use relevant util.
> Pose UI improvement

- peekingduck/cli.py
> Show version of peekingduck using peekingduck --version

- peekingduck/configs/output/csv_writer.yml
minor correction that output of csv_writer is none.
> fix(csv_writer.config): in config output should be none instead of end

- peekingduck/pipeline/nodes/draw/image_processor.py
Weird Pylint false positive. Make small difference to circumvent the issue.
> fix(draw): pylint issues with R0801 duplicate code

- peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
- peekingduck/pipeline/nodes/draw/tag.py
Part of issue #250. Update group bbox and tag functions to use newer implementation
> feat(refactor): refactor group bbox and tag

- __main__.py
- peekingduck/loaders.py
The change addresses the issue of not being able to locate the custom node folder in Windows.
Changed file path in \__main__\.py and loader.py.
> fix (core): Replace hard coding of config file path

- docs/source/getting_started/03_custom_nodes.md
- peekingduck/configs/output/media_writer.yml
- peekingduck/pipeline/nodes/output/csv_writer.py
- peekingduck/pipeline/nodes/output/media_writer.py
- peekingduck/pipeline/pipeline.py
- peekingduck/runner.py
- tests/pipeline/nodes/output/test_csv_writer.py
- tests/pipeline/nodes/output/test_media_writer.py
- tests/runner/test_runner.py
> refactor pipeline delete

- docs/_templates/class.rst
- peekingduck/pipeline/nodes/input/live.py
- peekingduck/pipeline/nodes/input/recorded.py
- peekingduck/pipeline/nodes/node.py
- peekingduck/pipeline/pipeline.py
Refactored the doc strings to describe pipeline , live node, recorded node and node
> docs(nodes): refactor doc strings for read the docs

- peekingduck/pipeline/nodes/model/yolo.py
Added docstrings for yolo node.
> Fix docstrings YOLO node

- docs/_templates/class.rst
- peekingduck/pipeline/nodes/heuristic/bbox_to_3d_loc.py
- peekingduck/pipeline/nodes/heuristic/check_large_groups.py
- peekingduck/pipeline/nodes/heuristic/check_nearby_objs.py
- peekingduck/pipeline/nodes/heuristic/group_nearby_objs.py
- peekingduck/pipeline/nodes/heuristic/keypoints_to_3d_loc.py
> Heuristics docstrings update for read the docs.

- peekingduck/configs/heuristic/fps.yml
Changed default for FPS moving average logging to True
Closes #352
> fix(refactor): changed fps logging to true

- scripts/run_tests.sh
> ci(cicd-infra): fixed bug to show coverage report

- .github/workflows/post_merge_checks.yml
- .github/workflows/pre_merge_ci.yml
> ci(cicd-infra): added windows to pre and post merge unit tests

- peekingduck/pipeline/nodes/draw/utils/bbox.py
- tests/pipeline/nodes/draw/test_bbox.py
- tests/pipeline/nodes/draw/test_btm_midpoint.py
- tests/pipeline/nodes/draw/test_group_bbox_and_tag.py
- tests/pipeline/nodes/draw/test_image_processor.py
- tests/pipeline/nodes/draw/test_legend.py
- tests/pipeline/nodes/draw/test_poses.py
- tests/pipeline/nodes/draw/test_tag.py
- tests/pipeline/nodes/draw/test_zones.py
Added Draw nodes tests. Closes #359 .
> Draw tests

- README.md
- diagrams/node_types.drawio.svg
- diagrams/yolo_demo.drawio.svg
- docs/source/introduction/01_introduction.md
> Changed 'heuristic' nodes to 'dabble' and updated colour scheme of diagrams

- README.md
- docs/source/introduction/01_introduction.md
Adds references to local, global IHL research papers and repositories used.
Closes #346
> additional references

- .readthedocs.yaml
update requirements to cicd_requirements.txt
> docs(requirements): update requirements in readthedocs.yaml

- README.md
- docs/source/index.rst
- docs/source/introduction/01_introduction.md
- docs/source/introduction/02_bibliography.md
PR for partial issue #370 (task 3) 
view on RTD:
> added bibliography section

- peekingduck/configs/model/yolo.yml
- peekingduck/pipeline/nodes/input/live.py
- peekingduck/pipeline/nodes/input/recorded.py
- peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_model.py
- peekingduck/pipeline/nodes/model/hrnet.py
- peekingduck/pipeline/nodes/model/hrnetv1/hrnet_model.py
- peekingduck/pipeline/nodes/model/posenetv1/posenet_model.py
- peekingduck/pipeline/nodes/model/yolov4/yolo_model.py
- peekingduck/pipeline/nodes/output/csv_writer.py
- peekingduck/pipeline/nodes/output/media_writer.py
This PR raises ValueError messages when certain config values are not met and thresholds are exceeded.
Closes #303
> Threshold error messages

- docs/source/use_cases/group_size_checking.md
- docs/source/use_cases/object_counting.md
- docs/source/use_cases/social_distancing.md
- docs/source/use_cases/zone_counting.md
> Update usecase markdowns

- .github/workflows/post_merge_checks.yml
- .github/workflows/pre_merge_ci.yml
Added the broken links check for premerge and post merge GitHub workflows
> test(cicd): added the broken link checks in pre and post merge GitHub workflow

- docs/source/conf.py
remove utils from appearing in rtd.
> docs (API ref): removed utils from being built

- README.md
- docs/source/getting_started/02_configure_pkdk.md
> docs (node_configs): Updated guide

- peekingduck/pipeline/nodes/node_template.py
> node (template): updated template to use kwargs

- docs/source/getting_started/03_custom_nodes.md
- peekingduck/cli.py
> Update custom nodes guide

- peekingduck/configloader.py
- peekingduck/declarative_loader.py
- peekingduck/runner.py
Docstrings for runner and loaders. Closes issue #326
> Docstring runner loaders

- peekingduck/pipeline/nodes/dabble/fps.py
> fix(fps): Ignore final frame in FPS calc to avoid skewing average

- docs/source/getting_started/01_installation.md
- docs/source/getting_started/02_configure_pkdk.md
- docs/source/getting_started/03_custom_nodes.md
- docs/source/getting_started/04_python_mode.md
Updated RTD Guides for clarity after testing by @ongzizhao and myself. 
Closes #377 #376
> Fix RTD guides after Testing 

- requirements.txt
- setup.cfg
Update shapely version to 1.7.1 to be the same as in requirements.txt
closed #423
> dependencies(setup.cfg): update shapely version to 1.7.1 same as requirement.txt

- peekingduck/configs/input/live.yml
- peekingduck/pipeline/nodes/input/live.py
> Fix linux threading

- README.md
> docs (README): changed images and hyperlinks to absolute links

- peekingduck/pipeline/nodes/model/yolo.py
Update the remove v3 and v3tiny in the comments for model type
> fix(model): remove v3 and v3tiny in the comments for model type

- CONTRIBUTING.md
- README.md
- docs/source/index.md
> Replaced Discord comms channel with AISG community forum

- peekingduck/utils/logger.py
- requirements.txt
This PR adds colour to the messages from logger. This PR has been tested on OSX, Window, VS code terminal and Jupyter notebook.
> Colored terminal output

- peekingduck/pipeline/nodes/draw/bbox.py
add show_labels config to rtd. Close #449.
> docs(draw): added show_labels config explanation to rtd

- peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
- peekingduck/pipeline/nodes/draw/utils/bbox.py
Adds optional bbox colour choice to fix draw bbox and draw group and tag situations. Closes #453
> 453 bbox color

- setup.cfg
This PR fixed the drifting error due to Colorama not added in setup.cfg
> Add colorama library to setup.cfg

- __main__.py
- peekingduck/cli.py
- peekingduck/utils/logger.py
> feat(logging): error messages are shown in red for clarity

- __main__.py
- peekingduck/__init__.py
- peekingduck/cli.py
- peekingduck/pipeline/nodes/input/recorded.py
- peekingduck/utils/logger.py
- tests/cli/test_cli.py
Reverts aimakerspace/PeekingDuck#520
> Revert "Support CLI parameter --log_level (and --config_path)"

- .github/workflows/daily_drift_checks.yml
- .github/workflows/post_merge_checks.yml
- .github/workflows/pre_merge_ci.yml
- pyproject.toml
- scripts/run_tests.sh
- scripts/update_version.sh
- tests/api/__init__.py
- tests/api/test_api.py
Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/7
Added API testing
> CI/CD tests for `import peekingduck` Python API mode

- docs/source/getting_started/01_installation.md
- docs/source/use_cases/group_size_checking.md
- docs/source/use_cases/social_distancing.md
- peekingduck/declarative_loader.py
- peekingduck/pipeline/nodes/dabble/zoningv1/zone.py
- peekingduck/pipeline/nodes/draw/btm_midpoint.py
- peekingduck/pipeline/nodes/draw/utils/general.py
- peekingduck/pipeline/nodes/input/utils/preprocess.py
- peekingduck/pipeline/nodes/model/efficientdet.py
- peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/utils/model_process.py
- peekingduck/pipeline/nodes/model/posenet.py
- peekingduck/pipeline/nodes/model/posenetv1/posenet_files/preprocessing.py
- peekingduck/pipeline/nodes/model/yolov4/yolo_files/models.py
- peekingduck/utils/requirement_checker.py
- peekingduck/weights_utils/downloader.py
- tests/conftest.py
- tests/pipeline/nodes/draw/test_btm_midpoint.py
- tests/pipeline/nodes/draw/test_legend.py
- tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
Did a spell check and corrected spelling errors in comments, code variables and documentation.
> Fix 28 spelling errors in code, comments and docs

- peekingduck/configloader.py
- tests/loaders/test_configloader.py
Added outstanding unit test for YoloX to test loading of master map file.
> Yolox load master map unit test

- scripts/check_links.py
Closes https://github.com/aimakerspace/PeekingDuck/issues/565
**Changes**:
- Test validity of external URLs using `requests` instead of `urllib`
- Recommended by [Python docs](https://docs.python.org/3/library/urllib.request.html). "Higher-level interface" suggests some of the nitty-gritty has already been handled for us.
- Some AISG URLs (both valid and invalid) were returning 403 errors under `urllib` and were omitted by mistake. `requests` handles this properly and returns `200` and `404` as expected.
- Expanded the range of response status codes to all 4xx codes which correspond to [client errors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)
- In line with the original intention of catching broken/misspelled URLs
- Add a 10 s timeout for `requests.get()` and consider …
> cicd: add timeout to check links

- peekingduck/cli.py
- peekingduck/runner.py
- scripts/benchmarks/readme.txt
- scripts/benchmarks/run_benchmarks.sh
- scripts/benchmarks/run_multipose_lightning.yml
- scripts/benchmarks/run_singlepose_lightning.yml
- scripts/benchmarks/run_singlepose_thunder.yml
- scripts/benchmarks/run_yolox_large_multi.yml
- scripts/benchmarks/run_yolox_large_single.yml
- scripts/benchmarks/run_yolox_medium_multi.yml
- scripts/benchmarks/run_yolox_medium_single.yml
- scripts/benchmarks/run_yolox_small_multi.yml
- scripts/benchmarks/run_yolox_small_single.yml
- scripts/benchmarks/run_yolox_tiny_multi.yml
- scripts/benchmarks/run_yolox_tiny_single.yml
- tests/cli/test_cli.py
Add basic benchmarking capability on CLI.
Benchmarking script and run config files are stored in `PeekingDuck/scripts/benchmarks/`,  video assets used are stored in subfolders within `PeekingDuck/images/benchmarking/`.
The benchmarking script is implemented using `bash` and `AWK`.
Calling `PeekingDuck/scripts/benchmarks/run_benchmarks.sh` will run models for object detection (YOLOX) and pose estimation (MoveNet) with the two video files `single_person.mp4` and `multiple_people.mp4`, after 5 (default) consecutive runs and report the average real time per run, startup delay and FPS.
Sample execution with output:
```
❯ scripts/benchmarks/run_benchmarks.sh
PeekingDuck Benchmarking
cmd = python __main__.py --config_path scripts/benchmarks/run_yolox_tiny_single.yml
Benchmarking over 5 …
```
> Benchmarking

- peekingduck/pipeline/nodes/input/visual.py
Fixes #663
**Change Made**
Add check that FPS is at most 200 so that invalid FPS values will not get passed in
> add check that fps is at most 200

- peekingduck/pipeline/nodes/draw/instance_mask.py
For your review and approval, please.
> docs: move pylint magic comment so that it does not appear in HTML page

- peekingduck/pipeline/nodes/model/posenetv1/posenet_files/detector.py
- peekingduck/pipeline/nodes/model/posenetv1/posenet_files/predictor.py
- peekingduck/pipeline/nodes/model/posenetv1/posenet_files/preprocessing.py
Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/76
> Fix: posenet `model_type` typing

- .github/workflows/assign_issue_to_project.yml
- CONTRIBUTING.md
- README.md
- docs/source/faq.rst
- docs/source/getting_started/03_custom_install.rst
- docs/source/index.rst
- docs/source/tutorials/01_hello_cv.rst
- docs/source/tutorials/05_calling_peekingduck_in_python.rst
- docs/source/use_cases/_template_use_case.rst
- docs/source/use_cases/crowd_counting.rst
- docs/source/use_cases/face_mask_detection.rst
- docs/source/use_cases/group_size_checking.rst
- docs/source/use_cases/object_counting_over_time.rst
- docs/source/use_cases/object_counting_present.rst
- docs/source/use_cases/people_counting_over_time.rst
- docs/source/use_cases/privacy_protection_faces.rst
- docs/source/use_cases/privacy_protection_license_plates.rst
- docs/source/use_cases/social_distancing.rst
- docs/source/use_cases/zone_counting.rst
- notebooks/calling_peekingduck_in_python.ipynb
- setup.cfg
- Update all references to `aimakerspace` to `aisingapore`
- Update function docstring example in `CONTRIBUTING` to `transforms.py`
Note:
Changes to `assign_issue_to_project.yml` can only be verified post migration and post merge
> Docs: aisingapore migration

- peekingduck/pipeline/nodes/draw/legend.py
Fix _get_config_types() for draw.legend based on latest changes
> fix: update _get_config_types() for draw.legend

- cicd_requirements.txt
- tests/pipeline/nodes/draw/test_instance_mask.py
> Fix: change scikit-image to v0.17.2 for Python v3.6 compatibility

- peekingduck/pipeline/nodes/model/mask_rcnn.py
> docs: correct formatting and grammar

- docs/source/getting_started/03_custom_install.rst
Closes https://github.com/aisingapore/PeekingDuck-Private/issues/92
> Docs: add typeguard to macOS install instructions
