.github/workflows/code_check.yml

Enable checks for pull request for opensource contributors. This means that github actions will run on pull requests even if the code was not originally on our branch.

ci(cicd-infra): enable pull request code check

---

peekingduck/configs/input/live.yml
peekingduck/pipeline/nodes/input/live.py

To add functionality for live camera feed to save a video after model processing. Added filename and fps as outputs for live.py
filename = webcamfeed.mp4. fps = user input in live.yml.
Closes #251

251 save live video

---

peekingduck/pipeline/nodes/output/media_writer.py

added timestamp to filename when saved in media writer. subsequent runs will not override the same saved file
closes #259

259 - added timestamp to file name

---

peekingduck/configs/input/live.yml
peekingduck/configs/input/recorded.yml
peekingduck/configs/output/screen.yml
peekingduck/pipeline/nodes/input/live.py
peekingduck/pipeline/nodes/input/recorded.py
peekingduck/pipeline/nodes/output/screen.py
peekingduck/pipeline/pipeline.py
peekingduck/runner.py
tests/pipeline/test_pipeline.py
tests/runner/test_runner.py

"pipeline_end" are the outputs of these 3 nodes. Usually set to `False`, but becomes `True` under these conditions:
1. In `input.recorded`, the last video file has been processed
2. In `input.live`, the live video gets interrupted, e.g. webcam removed
3. In `output.screen`, someone presses `q` to terminate the program
"pipeline_end" can be used as inputs in these nodes (some examples):
- Send a POST request to update that all videos have been processed
- Show the average FPS of the entire run on terminal
- Uploading all results somewhere when done
It's called `pipeline_end` instead of just `end`, to avoid confusing with `file_end` that lives locally within input.recorded that only checks if the video or image file has ended.
closes #242

Add "pipeline_end" attribute that can be used to execute tasks upon ending of pipeline.

---

peekingduck/configs/draw/bbox.yml
peekingduck/configs/draw/bbox_count.yml
peekingduck/configs/draw/btm_midpoint.yml
peekingduck/configs/draw/fps.yml
peekingduck/configs/draw/group_bbox_and_tag.yml
peekingduck/configs/draw/poses.yml
peekingduck/configs/draw/tag.yml
peekingduck/configs/draw/zone_count.yml
peekingduck/configs/draw/zones.yml
peekingduck/configs/input/live.yml
peekingduck/configs/input/recorded.yml
peekingduck/configs/output/media_writer.yml
peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
peekingduck/pipeline/nodes/draw/tag.py
peekingduck/pipeline/nodes/draw/zone_count.py
peekingduck/pipeline/nodes/draw/zones.py
peekingduck/pipeline/nodes/input/recorded.py
peekingduck/pipeline/pipeline.py
tests/pipeline/nodes/output/test_media_writer.py
tests/pipeline/test_pipeline.py

A new ["none"] output/input type for nodes that don't take in any input/output:
1. output.media_writer will return ["none"] instead of ["end"]
2. All draw nodes will return ["none"] instead of ["img"]
3. input.live and input.recorded will take in ["none"] instead of ["source"] 
["none"] sounds consistent with our wildcard type ["all"].
Closes #66 and #179.

Standardization of "end", "img" and "source" by replacing with "none"

---

__main__.py
peekingduck/cli.py
peekingduck/loaders.py
peekingduck/runner.py

This PR will provide the user with the flexibility to define their own name for their custom nodes folder. The technical approach is from the runconfig.yml, automatically pick up the custom node folder name. 
In addition, in the cli, option is provided to the user to define their own custom name or choose the default.

Unique custom folder name

---

tests/loaders/test_declarativeloader.py

This PR addresses the unit testing for Declarative Loader, specifically the way to locate custom folder name. 
In addition, more unit testing cases are also included to increase the coverage.

Fix unittest declarativeloader

---

.github/workflows/publish_pypi.yml

addresses first part of #252 which does a local installation and test before publishing is allowed.

ci(cicd-infra): add local test before build

---

peekingduck/pipeline/nodes/input/recorded.py

This PR addresses the logging message of 10% approximate processing for images. 
In addition, as a further notice, when an image does not have a cv2.CAP_PROP_FRAME_COUNT value, it returns a sys.maxsize().
Closes #304

Resolve incorrect approx_processed in logging

---

__main__.py
peekingduck/cli.py
peekingduck/loaders.py
peekingduck/runner.py
tests/loaders/test_declarativeloader.py
tests/runner/test_runner.py

1. Command:
```
peekingduck run --node_config "{'input.live': {'resize':{'do_resizing':True, 'width':320}}, 'model.yolo': {'yolo_score_threshold': 0.8,'what':False}}"
```
2. Added logging to tell users which keys have been successfully updated and which are not:
```
2021-07-13T16:09:13 peekingduck.loaders INFO:Config for node model.yolo is updated to: 'yolo_score_threshold': 0.8
2021-07-13T16:09:13 peekingduck.loaders WARNING:Config for node model.yolo does not have the key: what
```
closes #258

Add feature to change node config from cli

---

peekingduck/configs/input/live.yml
peekingduck/configs/input/recorded.yml
peekingduck/configs/output/media_writer.yml
peekingduck/pipeline/nodes/input/live.py
peekingduck/pipeline/nodes/input/recorded.py
peekingduck/pipeline/nodes/output/media_writer.py
tests/pipeline/nodes/output/test_media_writer.py

To clear any misunderstanding with another implementation of model fps where it is the fps of the processed frames.

update fps to saved_video_fps in live , recorded and media_writer nodes and config

---

peekingduck/pipeline/pipeline.py
peekingduck/runner.py
tests/pipeline/test_pipeline.py
tests/runner/test_runner.py

Current implementation, peekingduck run the nodes in the Pipeline. Changes to be made to let Runner run the nodes, prepare for future implementation of different Runner mode (sequential and parallel)
Suggestion:
Shifting the the Pipeline.execute method to Runner.run. Then Pipeline will just contain the initiated nodes and also the data pool.

refactor(runner and pipeline): shift the running of the nodes from pipeline to runner 

---

peekingduck/weights_utils/downloader.py

The arg description (i.e. url) did not seem to match the name of the arg (i.e. blob file). Made minor corrections to correct it.

docs (utils): correct arg description to match arg

---

peekingduck/pipeline/nodes/draw/bbox.py
peekingduck/pipeline/nodes/draw/group_bbox_and_tag.py
peekingduck/pipeline/nodes/draw/utils/bbox.py

Added unique colours for different objects that were detected. Note that bbox labels and show labels are made compulsory to accommodate the use of the labels to get the colour of each bbox. As such, minor changes are also made to group and tag to match these changes.

Bbox colours

---

README.md

Closes #399 
(3419ccf) The update to the link in References section will break until v1.0 is out. This is to be expected as the references were recently added.

Fix rtd links

---

scripts/check_links.py

There are some links with # in the html for it to reference another part of the html. 
Example `[here](./io_draw_nodes.md#input-nodes)` , where `./io_draw_nodes.md` is deprecated. 
An update is made to catch this type of links and check if it is valid.

test(cicd): include links with # in it

---

.github/workflows/post_merge_checks.yml
.github/workflows/pre_merge_ci.yml
tests/conftest.py
tests/pipeline/nodes/model/yolov4/test_yolo.py

Revert the previous commit  48aa098 in #378 
In github actions, windows 2016/2019 sometimes causes the post merge checks to fail. Currently do not have any idea what is causing the failure. 
Decision is to remove the windows check and also revert the changes made to the test fixtures in test_yolo in #378 
Future investigation on the root cause of Windows failure required before reinstating windows in the pre/post merge checks

Revert previous commit to change yolo test fixture

---

docs/source/getting_started/02_configure_pkdk.md
docs/source/getting_started/03_custom_nodes.md
docs/source/getting_started/04_python_mode.md

I have noticed some errors in the RTD guide and also some areas that require more clarification for the benefit of readers.
In the Getting Started > Changing Nodes and Settings > Configuring node behaviour > via CLI section:
- The guide suggested `input.live  : {'input_dir': <directory where videos/images are stored}`. 
- Input live node do not have input dir argument. should be replaced with input.recorded. 
- Also for the directory/filepath need to high light to be in apostrophe `  {'input.recorded'  : {'input_dir': '<directory where videos/images are stored>'}}`
- When testing in windows need to suggest to use `\\` rather than single `\` in the filepath 
- The example run_config.yml did not use output.media_writer but the `--node_config` example used it 
- Should highlight that updates …

docs(RTD): clarified some parts in the RTD documentation

---

scripts/check_type.sh

This would allow us to run type checking script locally and pass. The args included in pyproject.toml works for github actions, but not on local runs.
closes #464

cicd: added additional args to mypy script to match pyproject.toml

---

peekingduck/weights_utils/downloader.py

fix(downloader): changed url to download from gcp storage

---

peekingduck/runner.py
scripts/usecase_tests.sh
setup.cfg
tests/runner/test_runner.py

Fixes failing Daily Drift Checks.
**Issue description**:
Daily Drift Checks are failing with `FileNotFoundError: [Errno 2] No such file or directory: '/opt/hostedtoolcache/Python/3.6.15/x64/lib/python3.6/site-packages/peekingduck/optional_requirements.txt'`
**Investigation**:
`setup-python@v2` sets up `setuptools==40.6.2` by default while latest version at time of PR is `>=58.5.3`. Between these version, a [fix](https://setuptools.pypa.io/en/latest/history.html#v58-5-0) for inconsistency with `include_package_data` and `package_data` was made. [Details](https://github.com/pypa/setuptools/issues/1461).
Daily Drift Checks attempts to install `peekingduck` when `setuptools` is at the old version, this caused `optional_requirements.txt` to get omitted.
**Fix**:
The `[options.package_data]` …

Fix package data

---

peekingduck/pipeline/nodes/draw/mosaic_bbox.py

Closes https://github.com/aimakerspace/PeekingDuck/issues/519
Changes include:
- Change underlying mosaic algorithm to use 2x `cv2.resize()`
- A downsize to (`mosaic_level`, `mosaic_level`) followed by an upsize to the original size
- Change both `mosaic_bbox` and `mosaic` to private
- Convert `mosaic` to an instance method so it can access `self.mosaic_level` directly without have to be passed in as an argument
- Check that `bbox` coordinates are within bounds
There are some differences in the mosaiced output between the current implementation and PR implementation:
| Current | PR | Remarks |
|---------|----|---------|
| ![jim_curr](https://user-images.githubusercontent.com/56420072/142155866-1debe75e-df12-4998-8deb-f3b02e490770.gif) | …

Feat fast mosaic

---

peekingduck/pipeline/nodes/input/utils/read.py
tests/pipeline/nodes/input/test_input_threading.py

Fixes #531 with the following upgrades:
Improved threading unit test code to make it more robust:
1. Delete the destructive `os.chdir()` call.
2. Pass the working directory to `subprocess.Popen()` call instead.
3. Shifted the backup and restore of existing `run_config.yml` into a context manager to ensure resources are properly restored in the event of an exception or crash.
(tested by CTRL-C breaking the threading unit test)
Also took the chance to enable debug output in `input/utils/read.py` `VideoThread.__del__` as the `subprocess.Popen()` no longer crashes upon exit on Nvidia Jetson Xavier Ubuntu 18.04 (tested).

Fix post merge test failures

---

docs/make.bat

Closes #533 
Changes:
* Added `set READTHEDOCS=1` in make.bat, solves the `Extension Error` when building the sphinx html docs on Windows

Fixed sphinx error on Windows when building html

---

.github/workflows/publish_pypi.yml
.github/workflows/publish_skip_testpypi.yml

**Issue**:
The publish workflow is currently using `pypa/gh-action-pypi-publish@master` which uses the `master` branch pointer instead of being pinned to a specific tagged version.
The [recommendation](https://github.com/pypa/gh-action-pypi-publish#usage) from the PyPI publish repo is to pin to a tagged version for more reproducible/secure builds. *Note: the example given in the repo at the time of this PR is still using a branch pointer `version/v1` instead of a tagged version.*
**Changes:**
For reference, the [publish workflow](https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/publish_pypi.yml#L38) for scikit-learn pins to `v1.4.1`.
Based on the latest logs from PeekingDuck's publish workflow: 
```
Download action repository 'pypa/gh-action-pypi-publish@master' …
```

cicd: pin pypi-publish version to v1.4.2

---

__main__.py
peekingduck/cli.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/13
A detailed description of the issue faced and various use cases enabled by this PR can be found in the comments thread of the origin issue.
**Changes**:
- Change dev mode to invoke CLI `run()` command from `cli.py` with `click.pass_context`
- Make the call to `Runner.run()` more consistent, can avoid duplicating some of the pre-run setups.
- Set `custom_nodes_parent_subdir="src"` when running in dev mode with `config_path` option
- So that PKD will have access to `custom_nodes` in custom projects
- This will break workflows that keeps `custom_nodes` in the `PeekingDuck` directory **and** is calling with the `config_path` CLI option
- Simply calling `python PeekingDuck` will still work
- As a bonus, this PR also enables …

Feat: Run custom project/nodes in dev mode

---

peekingduck/configs/output/screen.yml
peekingduck/pipeline/nodes/output/screen.py

closes #543 
Summary of improvements:
1. Gives users the option to resize the output window via configs, for situations such as high-res videos on a small laptop screen, where not the entire output window can be seen
2. The window size can now also be adjusted by clicking and dragging the output window
3. The top left corner of the output window will now be at the top left corner of the screen by default. It can also be changed in the configs. Previously, the top left corner of the output window would be around the middle of my screen, and I always had to drag the output window up to see the whole thing.
4. Gives users the option to change the name of the output window, when previously it was fixed as "PeekingDuck"

Add configurable options to improve `output.screen` node

---

peekingduck/pipeline/nodes/draw/utils/bbox.py
peekingduck/pipeline/nodes/draw/utils/general.py
requirements.txt
setup.cfg

Closes #556. 
- `4.5.2.54` chosen due to factors mentioned in the issue.
- unpinned dependency version as a [good practice](https://stackoverflow.com/questions/28509481/should-i-pin-my-python-dependencies-versions) for releasing packages

Upgrade OpenCV version

---

docs/source/getting_started/03_custom_nodes.md
peekingduck/cli.py
peekingduck/declarative_loader.py
peekingduck/runner.py
peekingduck/utils/create_node_helper.py
peekingduck/utils/requirement_checker.py
tests/cli/test_cli.py
tests/cli/test_cli_create_node.py
tests/conftest.py
tests/data/user_configs/create_node.yml
tests/data/user_inputs/create_node.yml
tests/loaders/test_declarativeloader.py
tests/runner/test_runner.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/18
**Changes:**
- Add `--config_path` CLI option and its corresponding function argument `config_path` to `create-node` CLI command
- Implement a `NodeList` iterator class which yields `node_str` and `config_updates`. Assigned to the `node_list` member variable of `DeclarativeLoader`. `node_str` (e.g., `custom_nodes.dabble.fps`) is used by `create_node`.
- Avoid creating member variables specifically for `create-node` CLI
**How it works:**
- The user can pass in a run config file to create the declared custom nodes by using:
```
peekingduck create-node --config_path <path/to/config_file.yml>
```
1. Check that none of the `node_` related CLI options are used, raise `ValueError` if they are. The "create node by parsing …

Feat: create node parse config

---

docs/source/getting_started/03_custom_nodes.md

Closes https://github.com/aimakerspace/PeekingDuck/issues/568
Removed the extra `custom_nodes` folder, it should look like this now:

docs: fix directory structure in build custom nodes tutorial

---

peekingduck/pipeline/nodes/dabble/utils/tracking_files/opencv_tracking.py
requirements.txt
setup.cfg

Change dependency to `opencv-contri-python` so OpenCV (mosse) tracker can work.
Although this will be fixed in the MOT evaluation PR, that PR might take some time to pass. So this quick fix allows development on `node-v1.2` branch to continue.

fix: use opencv-contrib-python so opencv tracker works

---

__main__.py
peekingduck/cli.py
peekingduck/runner.py
tests/cli/test_cli.py
tests/runner/test_runner.py

[Re-open new PR with refreshed `node-v1.2` codebase]
New CLI option --num_iter to specify number of pipeline iterations. Pipeline run will stop upon reaching this number. If not specified (default behavior), pipeline will run indefinitely until a) the user manually terminates it or b) the input stream is exhausted.
Added this as it helps to have controlled, deterministic pipeline runs when profiling codes or conducting experiments.
Also request to help delete aborted, closed issue #570 (as I am unable to delete it).

Feature: `--num_iter` CLI option to stop pipeline after `num_iter` runs

---

docs/Makefile

Updated `docs/Makefile` with a new `clean:` section that removes previously generated `.rst` files in `source/` and clears the `build/` folder.
This allows a `make html` to be done from a clean slate, to eliminate warnings/errors caused by outdated (previously generated) `.rst` files.

Add clean: to makefile for 'make clean'

---

peekingduck/cli.py
peekingduck/utils/create_node_helper.py
tests/cli/test_cli_create_node.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/38
M1 Mac uses a later version of `click` which gives a different error message when user input is not in the predefined `Choice`s.
**Changes**
Re-raise invalid choice error (`BadParameter`) with a custom error message so it remains consistent across `click` versions.

Fix: failing cli create node tests on M1 Mac

---

docs/_templates/class.rst
docs/_templates/module.rst
docs/source/data_type.rst
docs/source/getting_started/02_configure_pkdk.md
docs/source/getting_started/03_custom_nodes.md
docs/source/getting_started/04_import_peekingduck.md
docs/source/index.md
docs/source/master.rst
docs/source/use_cases/crowd_counting.md
docs/source/use_cases/face_mask_detection.md
docs/source/use_cases/group_size_checking.md
docs/source/use_cases/human_tracking.md
docs/source/use_cases/multi_object_tracking.md
docs/source/use_cases/object_counting.md
docs/source/use_cases/privacy_protection_faces.md
docs/source/use_cases/privacy_protection_license_plate.md
docs/source/use_cases/social_distancing.md
docs/source/use_cases/zone_counting.md

Addresses https://github.com/aimakerspace/PeekingDuck-Private/issues/47
Removes the "extra" single entry class table, effectively reducing the number of clicks needed to get to the actual `Node` documentation.
Removed the more generic `peekingduck` API documentation, only show node related documentation.
Update references in various documents to point to the correct place. Since `peekingduck` API doc is removed, `peekingduck.pipeline.nodes` is replaced with a `_api_doc` anchor in `master.rst`. Added `{eval-rst}` to the affected lines in `.md` files so that the `:ref:` works properly.
Moved data type substitution to a separate file `docs/source/data_type.rst`.
NOTE: Made no attempt to beautify/format `.md` files since they will be converted to `.rst` later. Only made sure no references are …

Docs: remove extra click to node docs

---

.gitignore
docs/Makefile
docs/_templates/module.rst
docs/source/conf.py
docs/source/getting_started/03_custom_nodes.md
docs/source/master.rst
docs/source/use_cases/crowd_counting.md
docs/source/use_cases/face_mask_detection.md
docs/source/use_cases/human_tracking.md
docs/source/use_cases/object_counting.md
docs/source/use_cases/privacy_protection_faces.md
docs/source/use_cases/privacy_protection_license_plate.md
docs/source/use_cases/zone_counting.md

Closes https://github.com/aimakerspace/PeekingDuck/issues/576
- add peekingduck.pipeline.nodes to sys.path -> to omit the module prefix from the sidebar
- generate nodes docs in docs/source/nodes -> mostly for convenience in `make clean` target and gitignore
- add docs/source/nodes to "make clean" targer and gitignore
- omit module name in class signature for clarity
NOTE: while there is a way to modify the topbar (breadcrumbs), modifying it only for the API documentation pages does not seem straightforward and is not implemented https://docs.readthedocs.io/en/stable/guides/remove-edit-buttons.html?highlight=breadcrumb#remove-links-from-top-right-corner

docs: shorten module names in sidebar

---

.github/workflows/pre_merge_ci.yml
docs/source/glossary.rst
peekingduck/configs/node_template.yml

- Add more verbose explanation on the values to use for `input` and `output` in `node_template.yml`
- Explicitly mention that users can create custom data types for use with custom nodes in Glossary.
- Disabled `pip` cache in pre-merge CI

Docs: add explanation in node config template

---

.github/workflows/pre_merge_ci.yml

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/50
`setup-python` action [has been updated](https://github.com/actions/setup-python/issues/328#issuecomment-1030025436) to fix the cache issue on Windows.

cicd: enable pip cache in pre merge CI

---

peekingduck/cli.py
tests/cli/test_cli.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/49
Update the URLs printed by CLI command `nodes` based on latest documentation changes.

Fix: update CLI nodes URL

---

peekingduck/cli.py
pipeline_config.yml
tests/cli/test_cli.py

- Create verification pipeline file in `tempfile.TemporaryDirectory`
- Change `--verify_install` to stream from GCP
- Change `peekingduck init` to create `model.posenet` and `draw.poses` by default

feat: change --verify_install to use tempfile and stream from GCP

---

peekingduck/declarative_loader.py

Fix crashing bug when node is just `input.live`/`input.recorded` with no configurations.
Bug caused by `node.replace("live", "visual")`, `node.replace("recorded", "visual")` as Python string replace is not in-place.

bugfix: `input.visual` converter error for `input.live`/`input.recorded`

---

peekingduck/declarative_loader.py

`input.visual` converter left out `source:0` configuration for the deprecated `input.live`. This results in the green man video showing instead of the live webcam.
Also for anomalous `input.recorded` without configuration situation, will default to just `input.visual` which reads the green man video from PeekingDuck's cloud storage.

bugfix: 'input.visual' converter left out 'source:0' config

---

tests/pipeline/nodes/input/test_input_threading.py

The RTSP URL for input threading unit test went offline today.
Replaced it with another working RTSP URL.
Also capture two other URLs as standbys.

fix: broken RTSP URL in unit test, also prepare two others as standby

---

tests/pipeline/nodes/input/test_input_threading.py

Updated input threading unit test to run over a list of RTSP URLs (currently 3). Unit test will pass if any one of the URLs is tested successfully. This provides some redundancy in case the "regular" RTSP URL goes offline.

Run threading unit test over multiple RTSP URLs instead of just one

---

peekingduck/weights_utils/downloader.py

`tqdm` used by weights downloader outputs to `stderr` by default. This is fine for CLI usage.
However, for an app that `imports peekingduck...` and redirects `stderr` to monitor for errors, like PeekingDuckStudio for instance, then this is less than desirable, as:
1. The weights download output never appears for the user to see;
2. The app mistakes the weights download output in `stderr` stream for actual error messages.
Raise this PR to redirect `tqdm`'s output to use `stdout` instead of `stderr` to avoid the above problems.

Weights download: tqdm to stdout

---

peekingduck/pipeline/nodes/input/visual.py
tests/pipeline/nodes/input/test_visual.py

There's a bug in `input.visual` where if the source is a single image file, then `output["filename"]` is not set. This update fixes this bug and also includes a unit test to specifically test this scenario.

fix: 'input.visual' filename was not set if source is a single image

---

peekingduck/cli.py
tests/cli/test_cli_create_node.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/78
Forces the custom node directory to be relative to `path/to/pkd-project/src`

Fix: create custom node directory relative to `src/`

---

lint_requirements.txt
peekingduck/pipeline/nodes/augment/brightness.py
peekingduck/pipeline/nodes/augment/contrast.py
peekingduck/pipeline/nodes/base.py
peekingduck/pipeline/nodes/model/csrnetv1/csrnet_model.py
peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_model.py
peekingduck/pipeline/nodes/model/fairmotv1/fairmot_model.py
peekingduck/pipeline/nodes/model/hrnetv1/hrnet_model.py
peekingduck/pipeline/nodes/model/jdev1/jde_model.py
peekingduck/pipeline/nodes/model/movenetv1/movenet_model.py
peekingduck/pipeline/nodes/model/mtcnnv1/mtcnn_model.py
peekingduck/pipeline/nodes/model/posenetv1/posenet_model.py
peekingduck/pipeline/nodes/model/yolov4/yolo_model.py
peekingduck/pipeline/nodes/model/yolov4_face/yolo_face_model.py
peekingduck/pipeline/nodes/model/yolov4_license_plate/yolo_license_plate_model.py
peekingduck/pipeline/nodes/model/yoloxv1/yolox_model.py
requirements.txt
setup.cfg
tests/pipeline/nodes/augment/test_brightness.py
tests/pipeline/nodes/augment/test_contrast.py
tests/pipeline/nodes/base/test_threshold_checker_mixin.py
tests/pipeline/nodes/model/csrnetv1/test_csrnet.py
tests/pipeline/nodes/model/hrnetv1/test_hrnet.py
tests/pipeline/nodes/model/jdev1/test_jde.py
tests/pipeline/nodes/model/yolov4/test_yolo.py
tests/pipeline/nodes/model/yolov4_face/test_yolo_face.py
tests/pipeline/nodes/model/yolov4_license_plate/test_yolov4_license_plate.py
tests/pipeline/nodes/model/yoloxv1/test_yolox.py

Closes https://github.com/aimakerspace/PeekingDuck-Private/issues/83
Changes:
- Uses a string to represent the interval of valid values.
- Checks formatting of the interval string using regex (see details below).
The interval string must match `^[\[\(]\s*[-+]?(inf|\d*\.?\d+)\s*,\s*[-+]?(inf|\d*\.?\d+)\s*[\]\)]$`:
- `^`: Start of line
- `[\[\(]`: Either `[` or `(`
- `\s*`: Any whitespace characters between 0 and unlimited times
- `[-+]?`: `-` or `+` between 0 and 1 time
- `(inf|\d*\.?\d+)`: Either `inf` or a decimal number where having a digit before the period is optional, e.g., `.9`. [Ref](https://stackoverflow.com/a/12117062) comment by Chandranshu
- `\s*`: Whitespace
- `,`: Separator
- `\s*`: Whitespace
- `[-+]?(inf|\d*\.?\d+)`: Optional `-` or `+` with either `inf` or a decimal number …

Feat: threshold checker interval string

---

lint_requirements.txt

Fixes #656
Changes made: changed `opencv-contrib-python >= 4.5.2.54` in `lint_requirements.txt` to `opencv-contrib-python >= 4.5.2.54, != 4.5.4.58, <= 4.5.5.64`

Fixed OpenCV Lint Requirements

---

peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/opencv_tracker.py
tests/conftest.py
tests/pipeline/nodes/dabble/test_tracking.py
tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
tests/pipeline/nodes/model/jdev1/test_jde.py

Closes https://github.com/aimakerspace/PeekingDuck/issues/661
Only set `is_initialized=True` when there is actual detection. This ensures that [`prev_tracked_bboxes`](https://github.com/aimakerspace/PeekingDuck/blob/main/peekingduck/pipeline/nodes/dabble/trackingv1/tracking_files/opencv_tracker.py#L99) will be non-empty when `_match_and_track()` is called.

Fix: set is_initialized=True only when there is detection

---

.github/workflows/pre_merge_ci.yml
peekingduck/declarative_loader.py
tests/cli/test_cli.py
tests/cli/test_cli_create_node.py
tests/conftest.py
tests/pipeline/nodes/input/test_input_threading.py

The regular `peekingduck run --config_path pipeline.yml` looks for a local pipeline file `pipeline.yml`. The pipeline typically assumes required assets are found locally, within the pipeline file's directory.
However, the user could have multiple pipeline files in different folders, e.g.
```
parent/
|---- project_A/
|     |-- pipeline_A.yml
|     |-- proj_A.mp4
|---- project_B/
|-- pipeline_B.yml
|-- proj_B.mp4
```
Currently, while in `project_A/`, running `peekingduck run --config_path pipeline_A.yml` works, but running `peekingduck run --config_path /parent/project_B/pipeline_B.yml` fails, because the latter will not be able to locate the asset `proj_B.mp4`.
Solution implemented and changes:
* made internal change to `DeclarativeLoader` class to check: if pipeline config path is a full …

Support full config path

---

peekingduck/configs/output/screen.yml
peekingduck/pipeline/nodes/output/screen.py

Changes made to the behaviour of the `output.screen` node:
1. When `do_resizing` option is set to `True`, display window can now be initialized to the preset width and height specified in the config setting, and user can change the window size and aspect ratio in any way they want without affecting the subsequent run.
2. When `do_resizing` option is set to `False`, the display window will be initialized to the frame's aspect ratio and size, and user can change the window size and aspect ratio in any way they want without affecting the subsequent run. ~~and when the user uses the mouse the change the window size, it will maintain a fixed aspect ratio, (i.e. user can only change the window size by dragging the 2 vertical sides of the display window.)~~
3.  Minimum window size is set to …

fix: display window not initializing to the correct aspect ratio and size

---

peekingduck/configs/draw/legend.yml
peekingduck/pipeline/nodes/draw/legend.py
peekingduck/pipeline/nodes/draw/utils/legend.py
tests/pipeline/nodes/draw/test_legend.py

closes #675 and #676.
Main changes:
- Fixed bug where the legend box is very thin and doesn't stretch across the entire width of text for zone counting
- Added improvement where font size of text within legend box can now be configured as follows:
```
font: {
size: 0.7,
thickness: 2
}
```
Other improvements include removing most hardcoded variables in `utils/legend.py`.

Fix `draw.legend` legend box width and allow changing of font size and thickness

---

setup.cfg
setup.py

Fix `pip install .` problems for older systems (e.g. Nvidia Jetson Ubuntu 18.04):
- add back `node_template.yml` and `master_map.yml` to `setup.cfg` for older pip versions
- add dummy `setup.py` for systems that cannot use `pyproject.toml`

Fix setup.cfg, add setup.py

---

peekingduck/cli.py

Fixes `RecursionError` when doing `peekingduck --verify_install` on Windows.

Fix: change to original directory after running verify install

---

peekingduck/commands/core.py

Fixes `RecursionError` when doing `peekingduck --verify_install` on Windows.

Fix: change to previous directory after verify install is done

---

tests/pipeline/nodes/base/test_weights_downloader_mixin.py
tests/pipeline/nodes/dabble/test_camera_calibration.py
tests/pipeline/nodes/model/csrnetv1/test_csrnet.py
tests/pipeline/nodes/model/efficientdet_d04/test_efficientdet.py
tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
tests/pipeline/nodes/model/hrnetv1/test_hrnet.py
tests/pipeline/nodes/model/jdev1/test_jde.py
tests/pipeline/nodes/model/mask_rcnnv1/test_mask_rcnn.py
tests/pipeline/nodes/model/movenetv1/test_movenet.py
tests/pipeline/nodes/model/movenetv1/test_predictor.py
tests/pipeline/nodes/model/mtcnnv1/test_mtcnn.py
tests/pipeline/nodes/model/posenetv1/test_posenet.py
tests/pipeline/nodes/model/posenetv1/test_predictor.py
tests/pipeline/nodes/model/yolact_edgev1/test_yolact_edge.py
tests/pipeline/nodes/model/yolov4/test_yolo.py
tests/pipeline/nodes/model/yolov4_face/test_yolo_face.py
tests/pipeline/nodes/model/yolov4_license_plate/test_yolov4_license_plate.py
tests/pipeline/nodes/model/yoloxv1/test_yolox.py

Closes https://github.com/aisingapore/PeekingDuck-Private/issues/87
- Change all `config["root"]` in tests to be initialized as `PKD_DIR`
- Make MaskRCNN tests run on CPU only
- Apply `tmp_dir` fixture to `TestCameraCalibration` to clean up the extra `PeekingDuck/data` folder
- Use `isinstance()` for type checking in `TestCameraCalibration` instead of `type()` [ref](https://switowski.com/blog/type-vs-isinstance)

Fix: consistent pytest weights location

---

.github/workflows/daily_drift_checks.yml
.github/workflows/post_merge_checks.yml
.github/workflows/pre_merge_ci.yml
.github/workflows/publish_pypi.yml
.github/workflows/standup_bot.yml
peekingduck/declarative_loader.py
peekingduck/pipeline/nodes/output/screen.py
peekingduck/viewer/viewer.py
tests/pipeline/nodes/output/test_screen.py

Addresses https://github.com/aisingapore/PeekingDuck/issues/433
- Uses https://github.com/marketplace/actions/gabrielbb-xvfb-action to run `output.screen`tests in a headless environment
- `output.screen` tests are only run if the platform is Linux because xvfb does not work on other platforms.
- Refactored `output/screen.py` to have 2 constants `MIN_RENDER_SIZE` and `MIN_WINDOW_SIZE` as a workaround to OpenCV quirk
- The scale factor of 1.5 is arbitrary and can be updated if a larger value is required on other platforms/OSes
- Update GitHub runners to use `ubuntu-latest` and `windows-latest`

Cicd: output screen test on xvfb

---

.github/workflows/post_merge_checks.yml
.github/workflows/publish_pypi.yml

Use `xvfb` action to run post-merge tests in `post_merge_checks.yml` and local tests in `publish_pypi.yml`

Cicd: run post merge with xvfb

---

peekingduck/pipeline/nodes/base.py
peekingduck/pipeline/nodes/input/utils/preprocess.py
peekingduck/pipeline/nodes/input/utils/read.py
peekingduck/pipeline/nodes/input/visual.py
tests/pipeline/nodes/base/test_weights_downloader_mixin.py
tests/pipeline/nodes/draw/test_tag.py
tests/pipeline/nodes/input/test_input_threading.py
tests/pipeline/nodes/input/test_visual.py

Closes https://github.com/aisingapore/PeekingDuck-Private/issues/93
- Skips weights integrity check and prints warning on `ConnectionErrror`
- Prints warning about possible connectivity issues when `input.visual` source is a URL
- Make `VideoThread` and `VideoNoThread` inherit from `VideoReader`
- Abstract `read_frame()` and `queue_size` for the child classes to implement

Feat: skip integrity check if offline

---

peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/detector.py
peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_files/model_process.py
peekingduck/pipeline/nodes/model/efficientdet_d04/efficientdet_model.py
peekingduck/pipeline/nodes/model/fairmot.py
peekingduck/pipeline/nodes/model/fairmotv1/fairmot_files/tracker.py
peekingduck/pipeline/nodes/model/fairmotv1/fairmot_model.py
peekingduck/pipeline/nodes/model/hrnetv1/hrnet_model.py
peekingduck/pipeline/nodes/model/jde.py
peekingduck/pipeline/nodes/model/jdev1/jde_files/tracker.py
peekingduck/pipeline/nodes/model/jdev1/jde_model.py
peekingduck/pipeline/nodes/model/movenetv1/movenet_files/predictor.py
peekingduck/pipeline/nodes/model/mtcnnv1/mtcnn_files/detector.py
peekingduck/pipeline/nodes/model/posenetv1/posenet_files/predictor.py
peekingduck/pipeline/nodes/model/posenetv1/posenet_model.py
peekingduck/pipeline/nodes/model/yolact_edgev1/yolact_edge_files/detector.py
peekingduck/pipeline/nodes/model/yolov4/yolo_files/detector.py
tests/pipeline/nodes/model/fairmotv1/__init__.py
tests/pipeline/nodes/model/fairmotv1/test_fairmot.py
tests/pipeline/nodes/model/fairmotv1/test_tracker.py
tests/pipeline/nodes/model/jdev1/test_jde.py
tests/pipeline/nodes/model/movenetv1/test_movenet.py
tests/pipeline/nodes/model/movenetv1/test_predictor.py
tests/pipeline/nodes/model/posenetv1/test_posenet.py

Closes https://github.com/aisingapore/PeekingDuck-Private/issues/77
- `bboxes` are now always `np.ndarray` type, guaranteed to have a shape of `(N, 4)`
- Empty keypoints are returned explicitly with `np.empty(0)` instead of `np.array(var_name)` where `var_name = []`.
- Updated tests to check for the updates return values

Refactor: consistent output types

---

peekingduck/pipeline/nodes/input/utils/read.py

`input.visual` `mirror_image` not working when `threading` is `False` due to bug in `VideoNoThread->read_frame()`.
This PR fixes the bug.

bug fix: mirror_image not working when threading is False

---

peekingduck/pipeline/nodes/input/utils/read.py

Closes https://github.com/aisingapore/PeekingDuck-Private/issues/102
Remove debug print statement in `VideoThread.__del__()` as it crashes on python 3.7
Works on python 3.8+ though.

bug fix: VideoThread.__del__ crashes on python 3.7

---

cicd_requirements.txt

Fix bandit crash in linting checks according to https://github.com/PyCQA/bandit/pull/952

cicd: set constraint for importlib-metadata to prevent bandit crash
